[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.9.21,<0.10" ]

[project]
name = "micropattern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
  { name = "Stan", email = "zyyu@umich.edu" },
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "elpigraph-python>=0.3.4",
  "ete3>=3.1.3",
  "faicons>=0.2.2",
  "jupyter>=1.1.1",
  "jupyterlab>=4.5.4",
  "kaleido>=1.2.0",
  "loguru>=0.7.3",
  "muon>=0.1.7",
  "notebook>=7.5.3",
  "phate>=2.0.0",
  "plotly>=6.5.2",
  "pysam>=0.23.3",
  "ruamel-yaml>=0.19.1",
  "s3fs>=2026.2",
  "scanpy>=1.12",
  "scikit-image>=0.25.2",
  "scprep>=1.1",
  "scvi-tools>=1.4.1",
  "shiny>=1.5.1",
  "shinyswatch>=0.9.0",
  "tables>=3.11.1",
]
